data:
    path: datasets/MVSEC/h5/
    mode: gtflow_dt1 # gtflow_dt1/gtflow_dt4
    window: 1 # 1 for dt1, 0.25 for dt4
    window_eval: 15000 # not used

model:
    mask_output: True

metrics:
    name: [AEE, AE]  # FWL, RSAT, AEE, NEE, AE
    flow_scaling: 128

loader:
    batch_size: 1
    resolution: [160, 160] # H x W, if the resolution is smaller than the input one, frames and events will be cropped at the center
    std_resolution: [256, 256]
    augment: []
    gpu: 1

vis:
    enabled: False
    px: 400
    bars: True
    activity: False
    store: True
    store_interval: 5.0  # store every x seconds
    type: gradients # gradients or vectors

hot_filter:
    enabled: True
    max_px: 100
    min_obvs: 5
    max_rate: 0.8