data:
    path: /usr/scratch/badile13/amarchei/MVSEC_evflow/h5/
    mode: gtflow_dt1 # gtflow_dt1/gtflow_dt4
    window: 1 # 1 for dt1, 0.25 for dt4
    window_eval: 15000 # not used

model:
    mask_output: True
    encoding: cnt # voxel/cnt
    round_encoding: False # for voxel encoding
    num_bins: 2
    temporal_cnt: True # if True, use temporal cnt input encoding

metrics:
    name: [AEE, AE]  # AEE, NEE, AE
    flow_scaling: 8

loader:
    batch_size: 1
    resolution: [8, 8] # H x W, if the resolution is smaller than the input one, frames and events will be cropped at the center
    std_resolution: [256, 256]
    augment: []
    gpu: 0
    output_crop: False

vis:
    enabled: False
    px: 400
    bars: True
    activity: False
    store: False

hot_filter:
    enabled: True
    max_px: 100
    min_obvs: 5
    max_rate: 0.8