data:
    #path: /usr/scratch/badile13/amarchei/MVSEC_evflow/h5/
    path: datasets/MVSEC/h5/
    mode: gtflow_dt1 # gtflow_dt1/gtflow_dt4
    window: 1 # 1 for dt1, 0.25 for dt4
    window_eval: 15000 # not used

model:
    mask_output: True

metrics:
    name: [AEE, NEE, AE]  # FWL, RSAT, AEE, NEE, AE
    flow_scaling: 128

loader:
    batch_size: 1
    resolution: [256, 256] # H x W
    augment: []
    gpu: 1

vis:
    enabled: True
    px: 400
    bars: True
    activity: False
    store: False
    store_interval: 10.0  # store every x seconds
    type: vectors # gradients or vectors

hot_filter:
    enabled: True
    max_px: 100
    min_obvs: 5
    max_rate: 0.8