experiment: Fine-tuning

data:
    path: /usr/scratch/badile13/amarchei/training/ # path to dataset in the server
    #path: /scratch/msc25h1/training/ # path to dataset in my scratch
    mode: events # events
    window: 1000 # events
    window_loss: 10000 # events

model:
    name: LIFFireNet # for other models available, see models/model.py
    encoding: cnt # voxel/cnt
    round_encoding: False # for voxel encoding
    norm_input: False # normalize input
    num_bins: 2
    base_num_channels: 32
    kernel_size: 3
    activations: [arctanspike, arctanspike] # activations for ff and rec neurons
    mask_output: True
    temporal_cnt: False # if True, use temporal cnt input encoding
    quantization:
        enabled: False
        type: int8 # int8 or int16

spiking_neuron:
    leak: [0.0, 1.0]
    thresh: [0.0, 0.8]
    learn_leak: True
    learn_thresh: True
    hard_reset: True
    
loss:
    flow_regul_weight: 0.001
    clip_grad: 100.0 # set to Null to disable
    overwrite_intermediate: False

optimizer:
    name: Adam
    lr: 0.00002

loader:
    n_epochs: 50
    batch_size: 8
    resolution: [64, 64] # H x W
    std_resolution: [128, 128]
    augment: ["Horizontal", "Vertical", "Polarity"]
    augment_prob: [0.5, 0.5, 0.5]
    gpu: 2

vis:
    verbose: True
    enabled: False
    px: 400
    store_grads: False

hot_filter:
    enabled: False
    max_px: 100
    min_obvs: 5
    max_rate: 0.8