experiment: Default

data:
    #path: /usr/scratch/badile13/amarchei/training/ # path to dataset in the server
    path: /scratch/msc25h1/training/ # path to dataset in my scratch
    mode: events # events
    window: 1000 # events
    window_loss: 10000 # events

model:
    name: SNNtorch_FCLIF # fully connected SNN
    encoding: cnt # voxel/cnt
    round_encoding: False # for voxel encoding
    num_bins: 2
    mask_output: True
    
loss:
    flow_regul_weight: 0.001
    clip_grad: 100.0 # set to Null to disable
    overwrite_intermediate: False

optimizer:
    name: Adam
    lr: 0.0002

loader:
    n_epochs: 100
    batch_size: 8
    resolution: [128, 128] # H x W
    std_resolution: [128, 128]
    augment: ["Horizontal", "Vertical", "Polarity"]
    augment_prob: [0.5, 0.5, 0.5]
    gpu: 3

vis:
    verbose: True
    enabled: False
    px: 400
    store_grads: False

hot_filter:
    enabled: False
    max_px: 100
    min_obvs: 5
    max_rate: 0.8